version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
    volumes:
      - "./keycloak/data:/opt/keycloak/data"
      - "./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf"
      - "./certs/:/etc/ssl/certs/"
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-k", "https://localhost:8443/realms/moodle/.well-known/openid-configuration" ]
      interval: 30s
      timeout: 10s
      retries: 5
  synapse:
    image: "matrixdotorg/synapse:latest"
    volumes:
      - "./synapse_data:/data"
      - "./certs/:/etc/ssl/certs/"
    environment:
      SYNAPSE_SERVER_NAME: "synapse"
      SYNAPSE_REPORT_STATS: "yes"
    ports:
      - "8008:8008"
      - "8448:8448"
    depends_on:
      - keycloak
    restart: on-failure
  element:
    image: vectorim/element-web
    volumes:
      - "./element_data/config.json:/app/config.json"
      - "./element_data/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./certs/:/etc/ssl/certs/"
    ports:
      - "8081:8081"
    depends_on:
      - synapse
  mailhog:
    image: mailhog/mailhog
